[project]
name = "celery-prometheus"
version = "2.1.2"
description = "Celery with your own prometheus metrics"
authors = [{ name = "Guillaume Gauvrit", email = "guillaume@gandi.net" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["celery>=5.4.0,<6", "prometheus-client >=0.17,<1"]

[dependency-groups]
dev = ["celery>=5.4.0,<6", "mypy>=1.13.0,<2"]

[[tool.mypy.overrides]]
disallow_any_generics = true
disallow_untyped_defs = true
module = "celery_prometheus.*"

[[tool.mypy.overrides]]
module = ["celery.*"]
ignore_missing_imports = true

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = [
    "B",   # bug bear security warning
    "I",   # isort import order
    "F",   # pyflakes
    "UP",  # alter when better syntax is available
    "RUF", #  the ruff devleoper's own rules
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
