name: tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Uncomment this part in case unit tests joins the party
    # strategy:
    #   matrix:
    #     python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    #     poetry-version: ["1.4.0"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          # python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: latest
          # poetry-version: ${{ matrix.poetry-version }}

      - name: Setup the virtualenv for celery-prometheus
        run: poetry install --with dev

      - name: Check lint with Flake8
        run: |
          poetry run flake8 .

      - name: Check imports with isort
        run: |
          poetry run isort -c .

      - name: Check formatting with black
        run: |
          poetry run black -C .

      - name: Check typing with mypy
        run: |
          poetry run mypy src/celery_prometheus/
